import type {
  DownloadBrandCard,
  DownloadCategoryCard,
  DownloadListFile,
  DownloadModelFolder,
  SolutionCategory,
} from './data-types'

export const downloadHomeCategories: DownloadCategoryCard[] = [
  {
    title: 'Huawei',
    description: 'Open Huawei solution folders, service categories, and repair files.',
    href: '/solution-files.html?brand=huawei',
    kind: 'brand',
    brandId: 'huawei',
  },
  {
    title: 'Honor',
    description: 'Open Honor-only folders, targeted recovery flows, and download files.',
    href: '/solution-files.html?brand=honor',
    kind: 'brand',
    brandId: 'honor',
  },
  {
    title: 'AOS FIRMWARE',
    description: 'Open AOS firmware folders, service categories, and download files.',
    href: '/solution-files.html?brand=aos-firmware',
    kind: 'brand',
    brandId: 'aos-firmware',
  },
]

export const solutionCategories: SolutionCategory[] = [
  {
    id: 'huawei-removed-id',
    brandId: 'huawei',
    brandLabel: 'Huawei',
    title: 'Removed ID',
    description: 'Huawei account removal and Huawei ID bypass resources.',
  },
  {
    id: 'repair-chip-damage',
    brandId: 'huawei',
    brandLabel: 'Huawei',
    title: 'Repair Chip Damage',
    description: 'Huawei board repair resources for chip damage and hardware-side jobs.',
  },
  {
    id: 'fix-reboot',
    brandId: 'huawei',
    brandLabel: 'Huawei',
    title: 'Fix Reboot',
    description: 'Huawei reboot loop, startup repair, and recovery patch files.',
  },
  {
    id: 'xml-qualcomm',
    brandId: 'huawei',
    brandLabel: 'Huawei',
    title: 'XML Qualcomm',
    description: 'Huawei Qualcomm XML, loader, and rescue resources.',
  },
  {
    id: 'honor-removed-id',
    brandId: 'honor',
    brandLabel: 'Honor',
    title: 'Removed ID',
    description: 'Honor account removal and secure unlock files.',
  },
  {
    id: 'honor-fix-reboot',
    brandId: 'honor',
    brandLabel: 'Honor',
    title: 'Fix Reboot',
    description: 'Honor reboot repair, startup restore, and recovery flow packages.',
  },
  {
    id: 'honor-otg-file',
    brandId: 'honor',
    brandLabel: 'Honor',
    title: 'OTG File',
    description: 'Honor OTG update files and service-side recovery bundles.',
  },
  {
    id: 'honor-repair-imei',
    brandId: 'honor',
    brandLabel: 'Honor',
    title: 'Repair IMEI',
    description: 'Honor IMEI repair packages, XML helpers, and restore notes.',
  },
]

export const firmwareHuaweiCards: DownloadBrandCard[] = [
  { title: '1.Huawei Unlocked SIM', subtitle: 'Download Firmware', href: '/firmware.html', kind: 'huawei' },
  { title: '10.HUAWEI 1 CLICK FILE_1-6 APP', subtitle: '1 CLICK FILE_1-6 APP', href: '/firmware.html', kind: 'huawei' },
  { title: '2.HUAWEI MDM REMOVE FILE', subtitle: 'HUAWEI MDM REMOVE FILE', href: '/firmware.html', kind: 'huawei' },
  { title: '3.Huawei Firmware Update', subtitle: 'Download Firmware', href: '/huawei-update.html', kind: 'huawei' },
  { title: '4.HUAWEI Firmware Dump', subtitle: 'HUAWEI Firmware Dump', href: '/firmware.html', kind: 'huawei' },
  { title: '5.Huawei FRP Bypass FILE Android 9', subtitle: 'Huawei FRP Bypass FILE Android 9', href: '/firmware.html', badge: 'Gmail Fix', kind: 'huawei' },
  { title: '6.Huawei FRP Bypass FILE Android 10', subtitle: 'Huawei FRP Bypass FILE Android 10', href: '/firmware.html', badge: 'Gmail Fix', kind: 'huawei' },
  { title: '7.OEM FILE HUAWEI', subtitle: 'Download Firmware', href: '/firmware.html', kind: 'huawei' },
  { title: '8.HUAWEI COMBINATION FILE', subtitle: 'HUAWEI COMBINATION FILE', href: '/firmware.html', kind: 'huawei' },
  { title: '8.LOADER FILE', subtitle: 'LOADER FILE', href: '/firmware.html', kind: 'huawei' },
  { title: '9.HUAWEI CERT FILE', subtitle: 'HUAWEI CERT FILE', href: '/firmware.html', kind: 'huawei' },
  { title: 'FIX IMEI Huawei', subtitle: 'FIX IMEI Huawei', href: '/firmware.html', kind: 'huawei' },
  { title: 'Huawei MTK Dead Boot Repair', subtitle: 'Restore IMEI and Restore OEM', href: '/firmware.html', kind: 'huawei' },
  { title: 'Huawei Firmware For Install GMS', subtitle: 'GMS Support Flash', href: '/firmware.html', kind: 'huawei' },
  { title: 'Huawei FRP ALL MTK', subtitle: 'Download Firmware', href: '/firmware.html', badge: 'Gmail Fix', kind: 'huawei' },
  { title: 'HUAWEI GMS Service Update 2020', subtitle: 'HUAWEI GMS Service Update 2020', href: '/firmware.html', kind: 'huawei' },
  { title: 'HUAWEI ID FLASH FILE', subtitle: 'HUAWEI ID FLASH FILE', href: '/firmware.html', kind: 'huawei' },
  { title: 'Huawei iD New Security 10.0.0 Bypass', subtitle: 'New Security 10.0.0 Bypass', href: '/firmware.html', badge: 'HUAWEI ID', kind: 'huawei' },
  { title: 'Huawei iD New Security 10.1.0 Bypass File', subtitle: 'Download Firmware', href: '/firmware.html', badge: 'HUAWEI ID', kind: 'huawei' },
  { title: 'Huawei iD New Security 9.1.0 Bypass', subtitle: 'Security 9.1.0 Bypass', href: '/firmware.html', badge: 'HUAWEI ID', kind: 'huawei' },
  { title: 'Huawei iD Old Security Kirin710 9.0 Bypass', subtitle: 'Download Firmware', href: '/firmware.html', kind: 'huawei' },
  { title: 'Huawei ReBoard Software', subtitle: 'Board Software', href: '/firmware.html', kind: 'huawei' },
  { title: 'Huawei Tool', subtitle: 'Download Firmware', href: '/firmware.html', kind: 'tool' },
  { title: 'Huawei_Firmware_Unbrick', subtitle: 'Download Firmware', href: '/firmware.html', kind: 'huawei' },
]

export const huaweiUpdateFolders: DownloadModelFolder[] = [
  { title: 'HUAWEI Mate 10_ALP-L29', subtitle: 'Download Firmware', href: '/ana-an00.html' },
  { title: 'Huawei Y5II CUN-L22', subtitle: 'Huawei Y5II CUN-L22', href: '/ana-an00.html' },
  { title: 'MediaPad_T3 AGS-L09', subtitle: 'MediaPad_T3 AGS-L09', href: '/ana-an00.html' },
  { title: 'ABR-AL60', subtitle: 'ABR-AL60', href: '/ana-an00.html' },
  { title: 'ABR-L29', subtitle: 'ABR-L29', href: '/ana-an00.html' },
  { title: 'AGRK-L09', subtitle: 'AGRK-L09', href: '/ana-an00.html' },
  { title: 'AGS3-L09 MatePad T 10s', subtitle: 'AGS3-L09 MatePad T 10s', href: '/ana-an00.html' },
  { title: 'AGS3K-L29', subtitle: 'AGS3K-L29', href: '/ana-an00.html' },
  { title: 'AN00D', subtitle: 'AN00D', href: '/ana-an00.html' },
  { title: 'ANA-AN00', subtitle: 'ANA-AN00', href: '/ana-an00.html' },
  { title: 'ANA-N29', subtitle: 'ANA-N29', href: '/ana-an00.html' },
  { title: 'ANA-NX9 ANA-N29CB', subtitle: 'ANA-NX9', href: '/ana-an00.html' },
  { title: 'AQM-AL00', subtitle: 'AQM-AL00', href: '/ana-an00.html' },
  { title: 'BAH4-L09', subtitle: 'BAH4-L09', href: '/ana-an00.html' },
  { title: 'BAH4-L29', subtitle: 'BAH4-L29', href: '/ana-an00.html' },
  { title: 'BAH4-W09S', subtitle: 'BAH4-W09S', href: '/ana-an00.html' },
  { title: 'BAL-AL00', subtitle: 'BAL-AL00', href: '/ana-an00.html' },
  { title: 'BAL-L29', subtitle: 'BAL-L29', href: '/ana-an00.html' },
  { title: 'BAL-L49', subtitle: 'BAL-L49', href: '/ana-an00.html' },
  { title: 'BKL-L09', subtitle: 'BKL-L09', href: '/ana-an00.html' },
]

export const anaAn00Files: DownloadListFile[] = [
  {
    id: 'ana-an00-harmony3-remove-id',
    brandId: 'huawei',
    title: 'HUAWEI P40 Pro_ANA-AN00 (C00) Downgrade Firmware Harmony3.0 [Remove HUAWEI ID]',
    subtitle: 'HUAWEI P40 Pro_ANA-AN00 (C00) Downgrade Firmware Harmony3.0 [Remove HUAWEI ID]',
    summary: 'Downgrade package for Harmony3.0 with Huawei ID removal support.',
    date: '08-02-2024',
    size: '5.30 GB',
    visits: '454',
    downloads: '12',
    featured: true,
  },
  {
    id: 'ana-an00-emui11-05016',
    brandId: 'huawei',
    title: 'ANA-AN00 11.0.0.185(C00E180R8P2)_Firmware_EMUI11.0.0_05016EJP',
    subtitle: 'ANA-AN00 11.0.0.185(C00E180R8P2)_Firmware_EMUI11.0.0_05016EJP',
    summary: 'EMUI 11 firmware package for ANA-AN00 service restore.',
    date: '08-02-2024',
    size: '6.80 GB',
    visits: '388',
    downloads: '9',
    featured: true,
  },
  {
    id: 'ana-an00-harmonyos2-05016',
    brandId: 'huawei',
    title: 'ANA-AN00 102.0.0.268(C00E230R8P2)_Firmware_HarmonyOS 2.0.0_05016EJP',
    subtitle: 'ANA-AN00 102.0.0.268(C00E230R8P2)_Firmware_HarmonyOS 2.0.0_05016EJP',
    summary: 'HarmonyOS 2.0 package for ANA-AN00 recovery and restore.',
    date: '22-12-2023',
    size: '7.00 GB',
    visits: '512',
    downloads: '18',
    featured: true,
  },
  {
    id: 'ana-an00-product-combination',
    brandId: 'huawei',
    title: 'ANA-AN00 103.0.0.166(C00E160R8P8)_Product Combination Software_HarmonyOS 3.0.0_05016EJP',
    subtitle: 'ANA-AN00 103.0.0.166(C00E160R8P8)_Product Combination Software_HarmonyOS 3.0.0_05016EJP',
    summary: 'Product combination software for HarmonyOS 3 service operations.',
    date: '21-12-2023',
    size: '5.72 GB',
    visits: '431',
    downloads: '7',
    featured: true,
  },
]

export const solutionFilesByCategory: Record<string, DownloadListFile[]> = {
  'huawei-removed-id': [
    {
      id: 'removed-id-p40-harmony3',
      brandId: 'huawei',
      title: 'HUAWEI P40 Pro_ANA-AN00 (C00) Downgrade Firmware Harmony3.0 [Remove HUAWEI ID]',
      subtitle: 'Huawei P40 Pro_ANA-AN00 Harmony3 downgrade for Huawei ID removal',
      summary: 'Downgrade package for Harmony3.0 with Huawei ID removal support.',
      date: '08-02-2024',
      size: '5.30 GB',
      visits: '454',
      downloads: '12',
      featured: true,
    },
    {
      id: 'removed-id-huawei-nova11i',
      brandId: 'huawei',
      title: 'Huawei Nova 11i ID Reset and Recovery Bundle',
      subtitle: 'Nova 11i restore files for ID removal and recovery flow',
      summary: 'Recovery bundle for account removal and restore-side operations.',
      date: '18-02-2024',
      size: '3.86 GB',
      visits: '302',
      downloads: '8',
      featured: true,
    },
  ],
  'repair-chip-damage': [
    {
      id: 'chip-damage-p60-board',
      brandId: 'huawei',
      title: 'Huawei P60 Board Repair and Chip Damage Support Package',
      subtitle: 'Board repair package for Huawei P60 hardware-side recovery',
      summary: 'Support files and notes for chip damage repair work.',
      date: '03-03-2024',
      size: '2.44 GB',
      visits: '216',
      downloads: '6',
      featured: true,
    },
  ],
  'fix-reboot': [
    {
      id: 'fix-reboot-ana-an00',
      brandId: 'huawei',
      title: 'ANA-AN00 Reboot Loop Fix Firmware HarmonyOS 3.0',
      subtitle: 'Repair package for reboot loop and startup fix',
      summary: 'HarmonyOS firmware set for reboot loop and restart repair.',
      date: '19-02-2024',
      size: '6.20 GB',
      visits: '511',
      downloads: '14',
      featured: true,
    },
  ],
  'xml-qualcomm': [
    {
      id: 'xml-qualcomm-huawei-loader',
      brandId: 'huawei',
      title: 'Huawei Qualcomm XML Loader and Flash Package',
      subtitle: 'XML Qualcomm files for Huawei rescue and restore',
      summary: 'XML and loader set for Qualcomm board access workflows.',
      date: '01-03-2024',
      size: '1.48 GB',
      visits: '278',
      downloads: '9',
      featured: true,
    },
  ],
  'honor-removed-id': [
    {
      id: 'removed-id-honor-x9b',
      brandId: 'honor',
      title: 'HONOR X9b Secure ID Remove Package HarmonyOS',
      subtitle: 'Honor X9b account reset and secure unlock support package',
      summary: 'Security removal workflow for supported Honor X9b repair cases.',
      date: '11-02-2024',
      size: '4.12 GB',
      visits: '398',
      downloads: '17',
      featured: true,
    },
  ],
  'honor-fix-reboot': [
    {
      id: 'fix-reboot-honor-magic',
      brandId: 'honor',
      title: 'Honor Magic Reboot Repair and Recovery Set',
      subtitle: 'Recovery package for reboot and startup repair cases',
      summary: 'Recovery resources for Honor Magic reboot fix jobs.',
      date: '22-02-2024',
      size: '5.72 GB',
      visits: '323',
      downloads: '10',
      featured: true,
    },
  ],
  'honor-otg-file': [
    {
      id: 'otg-honor-service',
      brandId: 'honor',
      title: 'Honor OTG Recovery and Service Firmware',
      subtitle: 'OTG support package for Honor system restore',
      summary: 'Recovery and update package for OTG-side repair operations.',
      date: '14-02-2024',
      size: '3.94 GB',
      visits: '266',
      downloads: '9',
      featured: true,
    },
  ],
  'honor-repair-imei': [
    {
      id: 'repair-imei-honor-x',
      brandId: 'honor',
      title: 'Honor X Series IMEI Repair XML Bundle',
      subtitle: 'Honor IMEI repair and XML restore resources',
      summary: 'XML and support set for IMEI repair workflow.',
      date: '18-02-2024',
      size: '2.08 GB',
      visits: '244',
      downloads: '8',
      featured: true,
    },
  ],
}
